# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b94c1e79e569f35e02dadf725111a44dfc8f9a26df8fb133c70f2f5482f409f3875b4f549454f7ab2abeebc8f1ba990ce77d828f400dc720aec43a58a2703b3f

test:
  secret_key_base: d4e6443a50523a69e0b2c7700c04eedba1b803df934e36ff0b1c6094f673a19d1a80e70a42e6e90377a0504c18ee4c3f941b24d5d4662d21fb4c4e33bea7d418

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
